### ISSUE TITLE
issue with x64 windows!

### ISSUE THREAD

**Issue by sivaktamilan** [tmyroadctfig/twaindotnet#26]
Is this source run on (.net 4.0) windows x64 platform? when I run the source it throws me the below error: "An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B" 
Have anyone tried this? thanks.

**Comment by gigios** [comment]
The problem is that the 'normal' twain library is at 32bit and it is not possible to mix 32 and 64.
Unfortunately the scanners with a 64bit drivers are verly few.
I'm trying to create a bridge exe to allow the acquisition with the 'standard' 32bit in a 64bit application, probably this is the only way.

**Comment by shrikantjadhav5589** [comment]
Thanks @sivaktamilan. I gone through your article of Scanning. Everything is work perfect till now. Can I use your code for Commercial Purpose?

**Comment by sivaktamilan** [comment]
I was able to run the source in X64 mode, since I used the TWAINDSM.dll library which supports the X64 target platform on .net.
